use PRACTICE;

DESCRIBE BRANCH;

CREATE  TABLE BRANCH(
    BRANCH_ID INT  PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(30),
    ADDRESS VARCHAR(30)
);
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(30),
    JOB_DESCRIPTION VARCHAR(30),
    SALARY INT,
    BRANCH_ID INT,
    CONSTRAINT FK_BRANCH_ID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID)
);

DROP TABLE `BRANCH`;
ALTER  TABLE `EMPLOYEE` DROP FOREIGN KEY FK_BRANCH_ID;-- HERE WE CUT THE LINK BETWEEN TWO TABLE
DROP TABLE `EMPLOYEE`;